apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  labels:
    app: identity
  namespace: nebula
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
      - name: identity
        image: nebula/identity
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          name: identity
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: identity
  name: identity
  namespace: nebula
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32002
  selector:
    app: identity